### ISSUE TITLE
TypeError: unhashable type: 'list'  When trying to load lora

### ISSUE THREAD

**Issue by Revq** [altoiddealer/ad_discordbot#1]
``╭─────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────╮
│ N:\text-generation-webui-main\bot.py:328 in <module>                                                                    │
│                                                                                                                         │
│    327     if shared.args.lora:                                                                                         │
│ ❱  328         add_lora_to_model([shared.args.lora])                                                                    │
│    329                                                                                                                  │
│                                                                                                                         │
│ N:\text-generation-webui-main\modules\LoRA.py:18 in add_lora_to_model                                                   │
│                                                                                                                         │
│    17     else:                                                                                                         │
│ ❱  18         add_lora_transformers(lora_names)                                                                         │
│    19                                                                                                                   │
│                                                                                                                         │
│ N:\text-generation-webui-main\modules\LoRA.py:91 in add_lora_transformers                                               │
│                                                                                                                         │
│    90     prior_set = set(shared.lora_names)                                                                            │
│ ❱  91     added_set = set(lora_names) - prior_set                                                                       │
│    92     removed_set = prior_set - set(lora_names)                                                                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: unhashable type: 'list'``

When starting the bot.py with argument --lora test_lora1

**Comment by altoiddealer** [comment]
Hello, sorry for the delay in responding to this - I just realized the Issue now, and also that I was not subscribed to notifications :D

I should have this resolved in the next few days.

**Comment by altoiddealer** [comment]
> `╭─────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────╮ │ N:\text-generation-webui-main\bot.py:328 in <module> │ │ │ │ 327 if shared.args.lora: │ │ ❱ 328 add_lora_to_model([shared.args.lora]) │ │ 329 │ │ │ │ N:\text-generation-webui-main\modules\LoRA.py:18 in add_lora_to_model │ │ │ │ 17 else: │ │ ❱ 18 add_lora_transformers(lora_names) │ │ 19 │ │ │ │ N:\text-generation-webui-main\modules\LoRA.py:91 in add_lora_transformers │ │ │ │ 90 prior_set = set(shared.lora_names) │ │ ❱ 91 added_set = set(lora_names) - prior_set │ │ 92 removed_set = prior_set - set(lora_names) │ ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ TypeError: unhashable type: 'list'`
> 
> When starting the bot.py with argument --lora test_lora1

I just pushed a commit that should close this issue.

I'm not familiar with LLM Loras, can't seem to find one to test myself.  However, I found the error in the code and believe this should be resolved.

Please update and let me know.

**Comment by altoiddealer** [comment]
I'm closing that as completed.  Let me know if you have any further trouble.
