### ISSUE TITLE
statistics.yaml

### ISSUE THREAD

**Issue by Garry-Marshall** [altoiddealer/ad_discordbot#27]
ERROR [bot.ad_discordbot.modules.utils_files]: File not found: ad_discordbot\internal\statistics.yaml

If file does not exit, create empty file.

Cheers.

**Comment by altoiddealer** [comment]
Hello, thank you for the issue report.

I agree, this error does look scary - in the next update, I'll be sure this is changed to either Info or Warning that the file will be created.

I'll be focusing on making the bot more easily updateable, as soon as I can.  Let me know if you have any other issues.
Come [discuss the bot on discord](https://discord.com/channels/1089972953506123937/1154970156108365944) if you have any insights.
