### ISSUE TITLE
Feature Request: optionally tie model to character

### ISSUE THREAD

**Issue by Garry-Marshall** [altoiddealer/ad_discordbot#31]
As an optional option in a character file, tie a model to a character, so that when a certain character is loaded, a specific model loads as well.

**Comment by altoiddealer** [comment]
First - want to tell you that the error message you reported yesterday has been addressed.

Second - the install / update instructions changed.  I highly recommend checking those out.

**About this issue:**

This actually does exist already, but it's just not apparent.

By including a `change_llmmodel` tag in your character without a trigger, it will force change the model before ever generating text.

Here is an example from my coding character:

```
tags:
  - change_llmmodel: stable-code-instruct-3b
```

**If the current model is the same as the one triggered by tags, it will just print this in cmd window and nothing else:**

```
[TAGS] LLM model was triggered to change, but it is the same as current ("stable-code-instruct-3b").
```

The only drawback to this is that you won't be able to execute other `change_llmmodel` tags while the character is loaded, unless the tag definition has higher priority (Note: character tags are higher priority than Base and Imgmodel).

You could consider adding a trigger phrase to avoid that.

**Comment by Garry-Marshall** [comment]
Thanks for your reply, I'll look into that :)

**Comment by Garry-Marshall** [comment]
Update: works like a charm. Thanks again!
