### ISSUE TITLE
/sync is not awaited, causing bot to crash on use of the command

### ISSUE THREAD

**Issue by drakomatic** [altoiddealer/ad_discordbot#4]
Title says everything.

actual error:
```
RuntimeWarning: coroutine 'CommandTree.sync' was never awaited   self._context.run(self._callback, *self._args) RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by altoiddealer** [comment]
Thank you for the bug report - I’ll have a solution for this very shortly (by end of day)

**Comment by altoiddealer** [comment]
At some point I through this command in without paying much mind to it.

I have it tuned up now.  Please update to latest commit [2e4aaae](https://github.com/altoiddealer/ad_discordbot/commit/2e4aaae0fdadcb02d2a3b9d75a562974f1f29613) and let me know.

Thanks!

**Comment by drakomatic** [comment]
it appears to be working now

**Comment by altoiddealer** [comment]
Closing as completed
