### ISSUE TITLE
Command /speak throws error

### ISSUE THREAD

**Issue by Garry-Marshall** [altoiddealer/ad_discordbot#49]
Hey,
`/speak` now throws this error:

`18:09:15.137 #1852  ERROR [bot.__main__]: An error occurred in llm_gen(): 'NoneType' object has no attribute 'channel'
Traceback (most recent call last):
  File "E:\Python\oobabooga-windows\bot.py", line 1845, in llm_gen
    bot_history.manage_history(prompt=llm_payload['text'], reply=last_resp, save_to_history=save_to_history, chankey=str(i.channel.id))
                                                                                                                         ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'channel'`

**Comment by altoiddealer** [comment]
Hello, thanks for the Issue report.

I pushed a fix for this just now.

**Comment by Garry-Marshall** [comment]
Nice, works correct now!

**Comment by altoiddealer** [comment]
WOO!
