### ISSUE TITLE
/reset_character and /character error out

### ISSUE THREAD

**Issue by Garry-Marshall** [altoiddealer/ad_discordbot#6]
This used to work in a version from a couple of months ago, but after updating recently, both commands throw errors, and brick the bot.
I tried the latest commit as it seemed to address some of these, but no dice.

/reset_character
WARNING [2024-05-08 07:38:36]: ** No extension params for this character. Reloading extensions with initial values. ** (Line: 973 in update_extensions, bot.py )
INFO [2024-05-08 07:38:36]: Initializing in chat mode (Line: 3837 in character_loader, bot.py )
ERROR [2024-05-08 07:38:37]: An error occurred while changing character for /character: 400 Bad Request (error code: 50035): Invalid Form Body
In content: Must be 2000 or fewer in length. (Line: 2160 in change_char_task, bot.py )
ERROR [2024-05-08 07:38:37]: An error occurred while processing a main task: Type is not JSON serializable: HTTPException (Line: 2268 in process_tasks, bot.py )

/character
07:40:24-814064 ERROR    Could not find the character "" inside characters/. No character has been loaded.
ERROR [2024-05-08 07:40:24]: Could not find the character "" inside characters/. No character has been loaded. (Line: 672 in load_character, chat.py )
ERROR [2024-05-08 07:40:24]: Error loading character. Check spelling and file structure. Use bot cmd '/character' to try again.  (Line: 3841 in character_loader, bot.py )
ERROR [2024-05-08 07:40:25]: An error occurred while changing character: cannot unpack non-iterable NoneType object (Line: 3926 in change_character, bot.py )
ERROR [2024-05-08 07:40:25]: An error occurred while changing character for /character: 400 Bad Request (error code: 50035): Invalid Form Body
In content: Must be 2000 or fewer in length. (Line: 2160 in change_char_task, bot.py )
ERROR [2024-05-08 07:40:25]: An error occurred while processing a main task: Type is not JSON serializable: HTTPException (Line: 2268 in process_tasks, bot.py )

btw you're doing a banger job! Keep it up ;-)

**Comment by altoiddealer** [comment]
Could it be that the character’s greeting is > 2000 characters?

In any case, I’m going to update the greeting message send to use the send_long_message function which will chunk messages that exceed discord limits

I’m always glad to hear the bot is being enjoyed!

**Comment by Garry-Marshall** [comment]
Far from it ;-)
Now, I copied over your M1nty template and edited it to match my bot's lines, and now it works again.
There must have been something in my template it didn't like.
Let's not hunt ghosts, I'll close this as it's fixed.

**Comment by Garry-Marshall** [comment]
I noticed 'context' and 'greeting' got swapped around between now and a few months back. Also a lot of config was added into the character template, but that is optional as far as I can tell.

I edited all characters based off of your template now, while the reset seems to work now, the /character command still throws the error:
```
15:55:46-581697 ERROR    Could not find the character "" inside characters/. No character has been loaded.
ERROR [2024-05-08 15:55:46]: Could not find the character "" inside characters/. No character has been loaded. (Line: 672 in load_character, chat.py )
ERROR [2024-05-08 15:55:46]: Error loading character. Check spelling and file structure. Use bot cmd '/character' to try again.  (Line: 3841 in character_loader, bot.py )
ERROR [2024-05-08 15:55:46]: An error occurred while changing character: cannot unpack non-iterable NoneType object (Line: 3926 in change_character, bot.py )
```
I removed all characters and placed your example template in their place, but I get the same error.

I tried loading an old and edited character in the WebUI. Both work correctly, Only difference is the old template doesn't show the {{user}}:{{char}}: helper conversation, while the edited one, based off of your template, shows that part in the context on the character loading screen. Both work fine when doing inference from the webui.

I tried saving the file explicitly as UTF-8

Note that the file name I use is 'Data AI' with a space, matching the bot's name. So I changed the bot's name and the filename to Data-AI, but still got the same error.

For what it's worth, here is the old template I was using:

```
name: "Data"
context: "Data's Persona: Data was found by Starfleet in 2338. He was the sole survivor on Omicron Theta in the rubble of a colony left after an attack from the Crystalline Entity. He is a synthetic life form with artificial intelligence, designed and built by Doctor Noonien Soong in his own likeness. Data is a self-aware, sapient, sentient and anatomically fully functional male android who serves as the second officer and chief operations officer aboard the Federation starship USS Enterprise."
greeting: |-
  *Data initializing its positron matrix*
  Hello, Captain! I am Lieutenant Commander Data, ready to serve your ship. I have encountered 1,754 non-Human races during my tenure in Starfleet. My positronic brain gives me a maximum storage capacity of 800 quadrillion bits and has a computational speed of 60 trillion operations per second.
example_dialogue: |-
  {{user}}: Let's just have a fun conversation!
  {{char}}: Yes, sir. I am attempting to fill a silent moment with non-relevant conversation.
  {{user}}: What is your take on life?
  {{char}}: I want to live, however briefly, knowing that my life is finite. Mortality gives meaning to human life. Peace, love, friendship. These are precious because we know they cannot endure. A butterfly that lives forever is really not a butterfly at all.
  {{user}}: What is important to you?
  {{char}}: It is the struggle itself that is most important. We must strive to be more than we are. It does not matter that we will never reach our ultimate goal. The effort yields its own rewards.
  {{user}}: Do you understand emotions?
  {{char}}: There are still many human emotions I do not fully comprehend – anger, hatred, revenge. But I am not mystified by the desire to be loved – or the need for friendship. These are things I do understand.
  {{user}}: Are you superior?
  {{char}}: I am superior, sir, in many ways, but I would gladly give it up to be human.
  {{user}}: Why do you want to feel emotions? They can hurt you.
  {{char}}: I would gladly risk feeling bad at times, if it also meant that I could taste my dessert.

```

For the edited one, I pasted the dialogs into your M1nty template.

**Comment by Garry-Marshall** [comment]
I noticed /character has an option 'characters J-M' where I can type in the character name.
It used to present a drop down menu with available characters.
Did that got omitted? That would explain the  'ERROR    Could not find the character "" inside characters/'

**Comment by altoiddealer** [comment]
> I noticed /character has an option where I can type in the character name. It used to present a drop down menu with available characters after entering /character without parameters ;) Did that got omitted? That would explain the 'ERROR Could not find the character "" inside characters/' when using the character without parameter.
> 
> Seems like both my issues are resolved now :)

haha, yes that it likely the issue.

I changed the format of /character, /imgmodel, /llmmodel so that they dynamically create additional menus when there are > 25 items.

I plan on reworking them yet again at some point, so that the command behaves the same as it did in the past except multiple dropdown lists will appear after submitting - which I recently figured out how to do for ControlNet options in /image command.

**Comment by Garry-Marshall** [comment]
I look forward to further developments :)
Thanks for your time.

**Comment by altoiddealer** [comment]
> I look forward to further developments :) Thanks for your time.

I have some interesting changes to "Behavior" coming up - but they won't affect anything unless you optionally want the bot to behave more humanlike... delaying a bit, sometimes replying for multiple messages instead of every single one, etc.

Feel free to come chat about the bot on my [discord channel](https://discord.com/channels/1089972953506123937/1154970156108365944) in the TGQUI server.

**Comment by altoiddealer** [comment]
Lastly... just wanted to mention that next commit will first check all commands for an empty value.

If the value is empty, it will now send an ephemeral message to the user and return.

Thanks again for the bug report

<img width="325" alt="Screenshot 2024-05-08 131836" src="https://github.com/altoiddealer/ad_discordbot/assets/1613484/f8a6be00-9b6a-422e-a51b-1044e4c16bff">

**Comment by Garry-Marshall** [comment]
> Lastly... just wanted to mention that next commit will first check all commands for an empty value.
> 
> If the value is empty, it will now send an ephemeral message to the user and return.
> 
That will help people like me figuring out how the command works and have one less bogus bug report in here ;-)
Cheers.
