### ISSUE TITLE
Make bot send welcome message in the default channel instead of channels[0]

### ISSUE THREAD

**Issue by drakomatic** [altoiddealer/ad_discordbot#68]
make it so the bot sends the welcome message in the default (discord's welcome channel) instead of the first channel on the list
![image](https://github.com/altoiddealer/ad_discordbot/assets/79185478/9e363b1e-429b-44c2-a863-bb7d25dcc2e6)

**Comment by drakomatic** [comment]
btw loving the new features

**Comment by altoiddealer** [comment]
Good idea, I’ll first see if it can find channel named “general” before defaulting to first channel found.  Will add this on next commit.  Btw very nice improvements are coming to the new Context Menu commands (right click on discord messages)

**Comment by drakomatic** [comment]
I believe you can check what channel is the system message channel in the server settings and send it there

**Comment by altoiddealer** [comment]
Closed by #70
